UI changes for the MI dashboard
wso2/product-mi-tooling pull request #256
Opened 2022-03-02 08:02 UTC by UpekshaUdayaratne

## Purpose
Improve the user experience of the Integrator dashboard
Resolves https://github.com/wso2/micro-integrator/issues/2214, https://github.com/wso2/micro-integrator/issues/2177, https://github.com/wso2/micro-integrator/issues/2507, https://github.com/wso2/micro-integrator/issues/2395, https://github.com/wso2/micro-integrator/issues/2392.

## Goals
Change the Logout text to Sign Out
Change the Sign in text to Sign In
Adding a pop up to view the artifact details instead of the side drawer
Adding a search box to search loggers by the component name in the log configs tab
Improve dashboard to view faulty CApps
Bring in capabilities to manage server runtimes via dashboard

## Approach
![Sign Out](https://user-images.githubusercontent.com/65864330/156298034-28e4f5f2-c8b8-44ad-8a7a-143733c14db9.png)

![Sign In](https://user-images.githubusercontent.com/65864330/156298043-472a1b9b-19a6-4ba5-8f19-941230e7c2ee.png)

![Modal 1](https://user-images.githubusercontent.com/65864330/156298064-266cba86-4d48-44d1-8467-0c87ccdc86b1.png)

![Modal 2](https://user-images.githubusercontent.com/65864330/156298069-f23e861a-f9c4-4a19-b892-adda0af46339.png)

![Search Box](https://user-images.githubusercontent.com/65864330/156298088-8678eb44-368a-4cf8-a666-5b401d1d8fa4.png)

![Home Page](https://user-images.githubusercontent.com/65864330/177739264-2b556634-245b-4a43-beb2-dd75139c558c.png)

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2022-03-02 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/product-mi-tooling?pullRequest=256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/product-mi-tooling?pullRequest=256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/product-mi-tooling?pullRequest=256) it.</sub>

2022-05-23 05:54 UTC, chamilaadhi commented
@lasanthaS @UpekshaUdayaratne plz check and merge

2022-05-31 04:54 UTC, lasanthaS requested changes

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +var nodeStatus = "";
Make this single quotes('') instead of double("").

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +    nodeStatus=data.status;
Add spaces beside the equal sign.

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +
Remove blank line

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +
Remove blank line

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +        var message = 'Are you sure you want to '.concat(action).concat(' the node ').concat(nodeData.nodeId).concat('?')
Make sure the line length does not exceed 120 characters.

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +                status="shutdownGracefully";
Add spaces beside the equal sign

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +                status="shutdown";
Add single quotes instead of double quotes and spaces

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +        console.log(payload);
Remove this `console.log`

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +            // window.location.reload(true)
Remove commented-out code blocks

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +    return <div>
Let's wrap with brackets.

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/commons/TableRowCreator.js
> +}))(MenuItem);
Add empty line at the end of the file.

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/pages/LogConfigs.js
> +    const [searchQuery, setSearchQuery] = React.useState("");
Single quotes

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/pages/LogConfigs.js
> +        if (searchQuery){
Add space before the curly brace

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/pages/LogConfigs.js
> +            setFilteredLogConfigs(logConfigs.filter((logger)=>logger.componentName.includes(searchQuery)));
Spaces beside `=>`

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/pages/LogConfigs.js
> +        setSearchQuery("");
Single quotes

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/pages/LogConfigs.js
> +        float: "right",
Single quotes

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/utils/HTTPClient.js
> +        const url = basePath === "" ? AuthManager.getBasePath().concat(path) : basePath.concat(path);
Can replace this as follows.

```js
const url = (basePath === '' ? AuthManager.getBasePath() : basePath).concat(path);
```

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/utils/HTTPClient.js
> +        const path = '/server'
Add semicolon at the end of the line

2022-05-31 04:54 UTC, lasanthaS commented on monitoring-dashboard/components/org.wso2.micro.integrator.dashboard.web/web-app/src/utils/HTTPClient.js
> +        const basePath = 'http://localhost:9192/management'
Cannot merge the PR due to this. We need to find a proper way to get the hostname/port pair.

2022-07-12 08:30 UTC, sachithKay commented on monitoring-dashboard/components/org.wso2.ei.dashboard.core/src/main/java/org/wso2/ei/dashboard/core/rest/delegates/nodes/NodesDelegate.java
> +    public JsonObject manageNode(String groupId, String nodeId, ManageServerRuntimeRequest request) throws ManagementApiException {
lines shouldn't exceed 120 characters. verify formatting for the entire PR

2024-09-25 05:02 UTC, closed without merging

2024-09-25 05:02 UTC, chanikag commented
Closing due to conflicts.